[project]
name = "simple-name-parser"
version = "0.0.1"
description = "A simple class that parses names into their constituent parts"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
